switched back to building pnp4nagios using BuildRequires

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -148,56 +148,56 @@ jobs:
         name: Thruk RPMs
         path: ${{ steps.build.outputs.rpm_dir_path }}
 
-#  build-pnp4nagios:
-#    runs-on: ubuntu-latest
-#    steps:
-#    - uses: actions/checkout@v4
-#
-#    - name: Install dependencies
-#      run: sudo apt-get install -y rrdtool librrd-dev librrds-perl php-gd php-xml php-mbstring
-#
-#    - name: build PNP4Nagios packages
-#      id: build
-#      uses: UCBoulder/oit-sepe-rpmbuild@master
-#      with:
-#        spec_file: "pnp4nagios.spec"
-#        additional_repos: '["epel-release"]'
-#
-#    - name: Upload artifact
-#      uses: actions/upload-artifact@v4
-#      with:
-#        name: PNP4Nagios RPMs
-#        path: ${{ steps.build.outputs.rpm_dir_path }}
-
-  fetch-pnp4nagios:
+  build-pnp4nagios:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v4
 
-    - name: Create x86_64 directory
-      run: mkdir -p x86_64
+    - name: Install dependencies
+      run: sudo apt-get install -y rrdtool librrd-dev librrds-perl php-gd php-xml php-mbstring
 
-    - name: Fetch PNP4Nagios RPM
-      run: curl -L -o x86_64/pnp4nagios-0.6.27-5.alma.el8.x86_64.rpm https://github.com/pnp4nagios/pnp4nagios/releases/download/v0.6.27-5/pnp4nagios-0.6.27-5.alma.el8.x86_64.rpm
+    - name: build PNP4Nagios packages
+      id: build
+      uses: UCBoulder/oit-sepe-rpmbuild@master
+      with:
+        spec_file: "pnp4nagios.spec"
+        additional_repos: '["epel-release"]'
 
-    - name: debugging
-      run: |
-        if [ ! -f x86_64/pnp4nagios-0.6.27-5.alma.el8.x86_64.rpm ]; then
-          echo "Failed to download the PNP4Nagios RPM"
-          exit 1
-        else
-          echo "PNP4Nagios RPM fetched successfully"
-        fi
-
-    - name: List files in the current directory
-      run: ls -la
-
-    - name: Upload PNP4Nagios RPM as artifact
+    - name: Upload artifact
       uses: actions/upload-artifact@v4
       with:
         name: PNP4Nagios RPMs
-        path: ./x86_64/pnp4nagios-0.6.27-5.alma.el8.x86_64.rpm
-        if-no-files-found: error  # This ensures it fails if the file isn't found
+        path: ${{ steps.build.outputs.rpm_dir_path }}
+
+#  fetch-pnp4nagios:
+#    runs-on: ubuntu-latest
+#    steps:
+#    - uses: actions/checkout@v4
+#
+#    - name: Create x86_64 directory
+#      run: mkdir -p x86_64
+#
+#    - name: Fetch PNP4Nagios RPM
+#      run: curl -L -o x86_64/pnp4nagios-0.6.27-5.alma.el8.x86_64.rpm https://github.com/pnp4nagios/pnp4nagios/releases/download/v0.6.27-5/pnp4nagios-0.6.27-5.alma.el8.x86_64.rpm
+#
+#    - name: debugging
+#      run: |
+#        if [ ! -f x86_64/pnp4nagios-0.6.27-5.alma.el8.x86_64.rpm ]; then
+#          echo "Failed to download the PNP4Nagios RPM"
+#          exit 1
+#        else
+#          echo "PNP4Nagios RPM fetched successfully"
+#        fi
+
+#    - name: List files in the current directory
+#      run: ls -la
+#
+#    - name: Upload PNP4Nagios RPM as artifact
+#      uses: actions/upload-artifact@v4
+#      with:
+#        name: PNP4Nagios RPMs
+#        path: ./x86_64/pnp4nagios-0.6.27-5.alma.el8.x86_64.rpm
+#        if-no-files-found: error  # This ensures it fails if the file isn't found
 
   publish-rpms:
     if: ${{ startsWith(github.ref, 'refs/tags/') }}
