more testing more debugging. this process is awful

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -177,11 +177,24 @@ jobs:
     - name: Fetch PNP4Nagios RPM
       run: curl -L -o pnp4nagios-0.6.27-5.alma.el8.x86_64.rpm https://github.com/pnp4nagios/pnp4nagios/releases/download/v0.6.27-5/pnp4nagios-0.6.27-5.alma.el8.x86_64.rpm
 
+    - name: debugging
+      run: |
+      if [ ! -f pnp4nagios-0.6.27-5.alma.el8.x86_64.rpm ]; then
+      echo "Failed to download the PNP4Nagios RPM"
+      exit 1
+      else
+        echo "PNP4Nagios RPM fetched successfully"
+      fi
+
+    - name: List files in the current directory
+      run: ls -la
+
     - name: Upload PNP4Nagios RPM as artifact
       uses: actions/upload-artifact@v4
       with:
         name: PNP4Nagios RPMs
         path: ./pnp4nagios-0.6.27-5.alma.el8.x86_64.rpm
+        if-no-files-found: error  # This ensures it fails if the file isn't found
 
   publish-rpms:
     if: ${{ startsWith(github.ref, 'refs/tags/') }}
